onEvent('block.registry', event => {
    event.create('blockcasing_plain').material('stone').hardness(2).displayName('blockcasing_plain')
    event.create('overlay_circuitry').material('stone').hardness(2).displayName('overlay_circuitry')
    event.create('overlay_controller').material('stone').hardness(2).displayName('overlay_controller')
    event.create('overlay_firebox').material('stone').hardness(2).displayName('overlay_firebox')
    event.create('overlay_gearbox').material('stone').hardness(2).displayName('overlay_gearbox')
    event.create('overlay_energyinputhatch').material('stone').hardness(2).displayName('overlay_energyinputhatch')
    event.create('overlay_energyoutputhatch').material('stone').hardness(2).displayName('overlay_energyoutputhatch')
    event.create('overlay_fluidinputhatch').material('stone').hardness(2).displayName('overlay_fluidinputhatch')
    event.create('overlay_fluidoutputhatch').material('stone').hardness(2).displayName('overlay_fluidoutputhatch')
    event.create('overlay_inputbus').material('stone').hardness(2).displayName('overlay_inputbus')
    event.create('overlay_outputbus').material('stone').hardness(2).displayName('overlay_outputbus')
    event.create('overlay_vent').material('stone').hardness(2).displayName('overlay_vent')
    event.create('overlay_mana_input').material('stone').hardness(2).displayName('overlay_mana_input')
    event.create('overlay_mana_output').material('stone').hardness(2).displayName('overlay_mana_output')
})